### PR TITLE
Adding Extra Question Regarding Machine Learning and Deep Learning

### LINKED ISSUE #7: Adding Extra Question Regarding Machine Learning and Deep Learning
Supervised Learning:

Unsupervised Learning:

Deep Learning:

Evaluation and Metrics:

I have Some of the question under these topic ...

So Assign this issue to me under Hacktoberfest'23

### PR DESCRIPTION
**Pull request by Kapileswar-Moharana**
Issue Title: Adding Extra Question Regarding Machine Learning and Deep Learning
Issue Number: #7 

Close #7 

## Checklist:
- [x] I have mentioned the issue number in my Pull Request.
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy-to-understand README.md
- [x] The Questions work well on different devices.

## Description:

This pull request enhances the functionality of the "Flash Cards" in the document by adding smooth scrolling behavior and dynamic visibility based on the user's scroll position. Here are the key changes:

## Here is the Image  Illustration of the Feature:

Screenshot 2023-10-23 002606

### CODE REVIEW

**Comment by Kapileswar-Moharana** [comment]
@klaus78 Sir is there anything that You want to Change? If not then then Merge it Sir

**Comment by klaus78** [comment]
thank you very much @Kapileswar-Moharana!
Kindly add a star to the project.

**Comment by Kapileswar-Moharana** [comment]
> thank you very much @Kapileswar-Moharana!
> Kindly add a star to the project. 

Suree sure

**Comment by Kapileswar-Moharana** [comment]
@klaus78 Sir Kindly add The Hacktoberfest Accepted Lebel see 

### Screenshots   

Screenshot 2023-10-24 021509


Screenshot 2023-10-24 021654

**Comment by klaus78** [comment]
good now?

**Comment by Kapileswar-Moharana** [comment]
> good now?

Done

**Pull request merged**
